import { chartGlyph } from './chartedScript.js'

// An upright block alphabet for the typed writing, plainer and easier to
// read than the charted script: capitals and figures seven stitches tall,
// lowercase five, with two-stitch descenders. Charts are written as in
// chartedScript.js: the index of the row on the baseline, then the rows.
const LETTERS = {
  A: [6, ['.XXX.', 'X...X', 'X...X', 'XXXXX', 'X...X', 'X...X', 'X...X']],
  B: [6, ['XXXX.', 'X...X', 'X...X', 'XXXX.', 'X...X', 'X...X', 'XXXX.']],
  C: [6, ['.XXX.', 'X...X', 'X....', 'X....', 'X....', 'X...X', '.XXX.']],
  D: [6, ['XXXX.', 'X...X', 'X...X', 'X...X', 'X...X', 'X...X', 'XXXX.']],
  E: [6, ['XXXXX', 'X....', 'X....', 'XXXX.', 'X....', 'X....', 'XXXXX']],
  F: [6, ['XXXXX', 'X....', 'X....', 'XXXX.', 'X....', 'X....', 'X....']],
  G: [6, ['.XXX.', 'X...X', 'X....', 'X.XXX', 'X...X', 'X...X', '.XXXX']],
  H: [6, ['X...X', 'X...X', 'X...X', 'XXXXX', 'X...X', 'X...X', 'X...X']],
  I: [6, ['XXX', '.X.', '.X.', '.X.', '.X.', '.X.', 'XXX']],
  J: [6, ['..XXX', '...X.', '...X.', '...X.', '...X.', 'X..X.', '.XX..']],
  K: [6, ['X...X', 'X..X.', 'X.X..', 'XX...', 'X.X..', 'X..X.', 'X...X']],
  L: [6, ['X....', 'X....', 'X....', 'X....', 'X....', 'X....', 'XXXXX']],
  M: [6, ['X...X', 'XX.XX', 'X.X.X', 'X.X.X', 'X...X', 'X...X', 'X...X']],
  N: [6, ['X...X', 'X...X', 'XX..X', 'X.X.X', 'X..XX', 'X...X', 'X...X']],
  O: [6, ['.XXX.', 'X...X', 'X...X', 'X...X', 'X...X', 'X...X', '.XXX.']],
  P: [6, ['XXXX.', 'X...X', 'X...X', 'XXXX.', 'X....', 'X....', 'X....']],
  Q: [6, ['.XXX.', 'X...X', 'X...X', 'X...X', 'X.X.X', 'X..X.', '.XX.X']],
  R: [6, ['XXXX.', 'X...X', 'X...X', 'XXXX.', 'X.X..', 'X..X.', 'X...X']],
  S: [6, ['.XXXX', 'X....', 'X....', '.XXX.', '....X', '....X', 'XXXX.']],
  T: [6, ['XXXXX', '..X..', '..X..', '..X..', '..X..', '..X..', '..X..']],
  U: [6, ['X...X', 'X...X', 'X...X', 'X...X', 'X...X', 'X...X', '.XXX.']],
  V: [6, ['X...X', 'X...X', 'X...X', 'X...X', 'X...X', '.X.X.', '..X..']],
  W: [6, ['X...X', 'X...X', 'X...X', 'X.X.X', 'X.X.X', 'X.X.X', '.X.X.']],
  X: [6, ['X...X', 'X...X', '.X.X.', '..X..', '.X.X.', 'X...X', 'X...X']],
  Y: [6, ['X...X', 'X...X', '.X.X.', '..X..', '..X..', '..X..', '..X..']],
  Z: [6, ['XXXXX', '....X', '...X.', '..X..', '.X...', 'X....', 'XXXXX']],
  a: [4, ['.XXX.', '....X', '.XXXX', 'X...X', '.XXXX']],
  b: [6, ['X....', 'X....', 'XXXX.', 'X...X', 'X...X', 'X...X', 'XXXX.']],
  c: [4, ['.XXX.', 'X....', 'X....', 'X...X', '.XXX.']],
  d: [6, ['....X', '....X', '.XXXX', 'X...X', 'X...X', 'X...X', '.XXXX']],
  e: [4, ['.XXX.', 'X...X', 'XXXXX', 'X....', '.XXX.']],
  f: [6, ['..XX', '.X..', '.X..', 'XXX.', '.X..', '.X..', '.X..']],
  g: [4, ['.XXXX', 'X...X', 'X...X', 'X...X', '.XXXX', '....X', '.XXX.']],
  h: [6, ['X....', 'X....', 'X.XX.', 'XX..X', 'X...X', 'X...X', 'X...X']],
  i: [6, ['.X.', '...', 'XX.', '.X.', '.X.', '.X.', 'XXX']],
  j: [6, ['...X', '....', '..XX', '...X', '...X', '...X', '...X', 'X..X', '.XX.']],
  k: [6, ['X...', 'X...', 'X..X', 'X.X.', 'XX..', 'X.X.', 'X..X']],
  l: [6, ['XX.', '.X.', '.X.', '.X.', '.X.', '.X.', 'XXX']],
  m: [4, ['XX.X.', 'X.X.X', 'X.X.X', 'X...X', 'X...X']],
  n: [4, ['X.XX.', 'XX..X', 'X...X', 'X...X', 'X...X']],
  o: [4, ['.XXX.', 'X...X', 'X...X', 'X...X', '.XXX.']],
  p: [4, ['XXXX.', 'X...X', 'X...X', 'X...X', 'XXXX.', 'X....', 'X....']],
  q: [4, ['.XXXX', 'X...X', 'X...X', 'X...X', '.XXXX', '....X', '....X']],
  r: [4, ['X.XX.', 'XX..X', 'X....', 'X....', 'X....']],
  s: [4, ['.XXXX', 'X....', '.XXX.', '....X', 'XXXX.']],
  t: [6, ['.X..', '.X..', 'XXXX', '.X..', '.X..', '.X..', '..XX']],
  u: [4, ['X...X', 'X...X', 'X...X', 'X..XX', '.XX.X']],
  v: [4, ['X...X', 'X...X', 'X...X', '.X.X.', '..X..']],
  w: [4, ['X...X', 'X...X', 'X.X.X', 'X.X.X', '.X.X.']],
  x: [4, ['X...X', '.X.X.', '..X..', '.X.X.', 'X...X']],
  y: [4, ['X...X', 'X...X', 'X...X', 'X...X', '.XXXX', '....X', '.XXX.']],
  z: [4, ['XXXXX', '...X.', '..X..', '.X...', 'XXXXX']],
  0: [6, ['.XXX.', 'X...X', 'X..XX', 'X.X.X', 'XX..X', 'X...X', '.XXX.']],
  1: [6, ['.X.', 'XX.', '.X.', '.X.', '.X.', '.X.', 'XXX']],
  2: [6, ['.XXX.', 'X...X', '....X', '...X.', '..X..', '.X...', 'XXXXX']],
  3: [6, ['XXXXX', '...X.', '..X..', '...X.', '....X', 'X...X', '.XXX.']],
  4: [6, ['...X.', '..XX.', '.X.X.', 'X..X.', 'XXXXX', '...X.', '...X.']],
  5: [6, ['XXXXX', 'X....', 'XXXX.', '....X', '....X', 'X...X', '.XXX.']],
  6: [6, ['..XX.', '.X...', 'X....', 'XXXX.', 'X...X', 'X...X', '.XXX.']],
  7: [6, ['XXXXX', '....X', '...X.', '..X..', '.X...', '.X...', '.X...']],
  8: [6, ['.XXX.', 'X...X', 'X...X', '.XXX.', 'X...X', 'X...X', '.XXX.']],
  9: [6, ['.XXX.', 'X...X', 'X...X', '.XXXX', '....X', '...X.', '.XX..']],
  '.': [0, ['X']],
  ',': [0, ['.X', 'X.']],
  '!': [6, ['X', 'X', 'X', 'X', 'X', '.', 'X']],
  '?': [6, ['.XXX.', 'X...X', '....X', '...X.', '..X..', '.....', '..X..']],
  "'": [6, ['X', 'X']],
  '’': [6, ['X', 'X']],
  '"': [6, ['X.X', 'X.X']],
  ':': [4, ['.', 'X', '.', '.', 'X']],
  ';': [4, ['..', '.X', '..', '..', '.X', 'X.']],
  '-': [4, ['...', '...', 'XXX']],
  '(': [6, ['.X', 'X.', 'X.', 'X.', 'X.', 'X.', '.X']],
  ')': [6, ['X.', '.X', '.X', '.X', '.X', '.X', 'X.']],
  '/': [6, ['....X', '...X.', '...X.', '..X..', '.X...', '.X...', 'X....']],
  '&': [6, ['.XX..', 'X..X.', 'X.X..', '.X...', 'X.X.X', 'X..X.', '.XX.X']],
  '+': [4, ['.X.', 'XXX', '.X.']],
}

// Stitches between words, so they read apart at a glance.
export const SPACE_ADVANCE = 4

export const CHARTED_BLOCK = new Map(
  Object.entries(LETTERS).map(([letter, chart]) => [letter, chartGlyph(chart)]),
)
