// A charted script alphabet for the stitched writing, copied cell for cell
// from a filet/cross-stitch alphabet chart. Each letter is listed as rows of
// its chart, X for a filled block, with the index of the row that sits on
// the baseline; rows after it are descenders.
const LETTERS = {
  A: [6, [
    '.........XX',
    '........X..X',
    '.......X..X',
    '.X....X..X',
    'X.X..X.XX',
    'X...X...X..X',
    '.XXX.....XX',
  ]],
  a: [3, [
    '..XX.X',
    '.X..X',
    'X..X',
    'XXX.X',
  ]],
  B: [6, [
    '.....XXXX',
    '...XX..X.X',
    '..X...X..X',
    '.....XXXX',
    '.....X...X',
    'X...XX...X',
    '.XXX..XXX',
  ]],
  b: [6, [
    '...X',
    '...X',
    '..X',
    '.XXXX',
    '.X..X',
    'X..X',
    'XXX',
  ]],
  C: [6, [
    '....XXX',
    '..XX...X',
    '.X...XX',
    'XX',
    'X',
    'X...X',
    '.XXX',
  ]],
  c: [3, [
    '..XXX',
    '.X..X',
    'X',
    'XXX',
  ]],
  D: [6, [
    '....XXX..XX',
    '..XX...XX',
    '......X..X',
    '.....X...X',
    '.XX.X....X',
    'X..XX...X',
    '.XXX.XXX',
  ]],
  d: [6, [
    '......X',
    '.....X',
    '.....X',
    '..XXX',
    '.X..X',
    'X..X',
    'XXX.X',
  ]],
  E: [6, [
    '....XXX',
    '...X..X',
    '...XX',
    '.XX',
    'X',
    'X....X',
    '.XXXX',
  ]],
  e: [4, [
    '..XX',
    '.X.X',
    'XXX',
    'X',
    '.XX',
  ]],
  F: [7, [
    '..........X',
    '....XXXXXX',
    '..XX...X',
    '.X....X',
    '....XXXX',
    '.....X',
    'X...X',
    '.XXX',
  ]],
  f: [5, [
    '.......XXX',
    '......X...X',
    '....XXX.XX',
    '.....X',
    '....X.X',
    '....XX',
    '...X',
    '..XX',
    '.XX',
    'X.X',
    'XX',
  ]],
  G: [6, [
    '.....XXX',
    '...XX...X',
    '..X...XX',
    '..X',
    '.X....X',
    '.X...X',
    '..XXXX',
    'X...X',
    '.XXX',
  ]],
  g: [3, [
    '..XXX.X',
    '.X..XX',
    'X...X',
    '.XXXXX',
    '...X',
    '..XX',
    '.X.X',
    '.XX',
  ]],
  H: [6, [
    '.....XX.X..XX',
    '...X...X..X..X',
    '......X..X..X',
    '.....XXXXXXX',
    '.XXXXX..X',
    'X...X...X..X',
    '.XXX.....XX',
  ]],
  h: [6, [
    '....X',
    '...X',
    '...X',
    '..X.XX',
    '..XX.X',
    '.X...X',
    'XX..X',
  ]],
  I: [7, [
    '......X',
    '.....X.X',
    '....X.X',
    '.....X..X',
    '....XXXX',
    '.XX.X',
    'X..X',
    '.XX',
  ]],
  i: [5, [
    '.X',
    '.',
    'XX',
    '.X',
    'X',
    'XX',
  ]],
  J: [6, [
    '.....XXXX',
    '...XX..X',
    '..X...X',
    '..X..XX',
    '...X.X',
    'X...X',
    '.XXX',
  ]],
  j: [5, [
    '.....X',
    '.',
    '.....X',
    '...XX',
    '...X',
    '...XX',
    '..X',
    'XXX',
    'X.X',
    'XX',
  ]],
  K: [6, [
    '.....XXXX..XX',
    '....X..X..X..X',
    '...X..X..X',
    '.....XXXX',
    '.....X...X',
    'X...X....X..X',
    '.XXX......XX',
  ]],
  k: [6, [
    '....X',
    '...X',
    '...X.XX',
    '..X.X',
    '..XX',
    '.X..X.X',
    'XX..XX',
  ]],
  L: [6, [
    '........XX',
    '.......X..X',
    '......X...X',
    '......X.XX',
    '.XX..X',
    'X..XX....X',
    '.XX..XXXX',
  ]],
  l: [6, [
    '...X',
    '..X',
    '..X',
    '.X',
    '.X',
    'X..X',
    'XXX',
  ]],
  M: [6, [
    '.........X...X',
    '........XX..X',
    '.......XX..XX',
    '......X.X.XX..X',
    '.....X.X.X.X...X',
    'X..XX..XX..X...X',
    '.XX...X.....XXX',
  ]],
  m: [3, [
    'XX.XX.XXX',
    '..X..X..X',
    '.X..X..X',
    'XX.XX..XX',
  ]],
  N: [6, [
    '.........X...XX',
    '........XX..X.X',
    '.......XX..X..X',
    '......X.X.X..X',
    '.....X..XX',
    'X..XX..XX',
    '.XX....X',
  ]],
  n: [3, [
    'XX.XXX',
    '..X..X',
    '.X..X',
    'XX..XX',
  ]],
  O: [6, [
    '....XXX',
    '..XX...X',
    '.X.....X',
    'X......X',
    'X.....X',
    'X...XX',
    '.XXX',
  ]],
  o: [3, [
    '.XX',
    'X.X',
    'X.X',
    'XX',
  ]],
  P: [6, [
    '....XXXXX',
    '..XX..X..X',
    '.X...X...X',
    '.....X.XX',
    '....XX',
    'X...X',
    '.XXX',
  ]],
  p: [3, [
    '.XX.XXX',
    '...X..X',
    '..X..X',
    '..XXX',
    '.X',
    '.X',
    'X',
    'X',
  ]],
  Q: [6, [
    '....XXX',
    '..XX...X',
    '.X.....X',
    'X......X',
    'X...X.X',
    'X...XX..X',
    '.XXX..XX',
  ]],
  q: [3, [
    '..XXX.X',
    '.X..XX',
    'X...X',
    'XXXX',
    '...X',
    '...X',
    '..X',
    '...X',
  ]],
  R: [6, [
    '.....XXXXX',
    '....X..X..X',
    '...X..X...X',
    '.....XXXXX',
    '.....X..X',
    'X...X...X..X',
    '.XXX.....XX',
  ]],
  r: [3, [
    'XX.XX',
    '.XX.X',
    '.X',
    'XX',
  ]],
  S: [6, [
    '...XXX',
    '..X...X',
    '..X...X',
    '...X',
    'X...X',
    'X...X',
    '.XXX',
  ]],
  s: [3, [
    '..XXX',
    '..X',
    '...X',
    'XXX',
  ]],
  T: [6, [
    '....XXXXXXX',
    '..XX...X',
    '.X....X',
    '.....XX',
    '.....X',
    'X...X',
    '.XXX',
  ]],
  t: [5, [
    '..X',
    'XXXX',
    '.X',
    'X',
    'X..X',
    'XXX',
  ]],
  U: [6, [
    '.XX....X',
    'X..X...X',
    '...X..X',
    '..X...X',
    '.X...X',
    '.X..XX..X',
    '..XX..XX',
  ]],
  u: [3, [
    'XX..XX',
    '.X..X',
    'X..X',
    'XXX.XX',
  ]],
  V: [6, [
    '.XX...XX',
    'X..X..X.X',
    '...X....X',
    '..X....X',
    '.X....X',
    '.X..XX',
    '..XX',
  ]],
  v: [3, [
    'XX.XX',
    '.X..X',
    'X..X',
    'XXX',
  ]],
  W: [6, [
    '.XX....X...XX',
    'X..X..X...X..X',
    '..X..XX..X...X',
    '..X.X.X.X...X',
    '.X.X.X.X',
    '.XX..XX',
    'X...X',
  ]],
  w: [3, [
    'XX..X.XX',
    '.X..X..X',
    'X..X..X',
    'XXX.XX',
  ]],
  X: [7, [
    '..XXX.XX',
    '.X...X..X',
    '.....X',
    '.....X',
    '...XXXX',
    '....X',
    'X..XX...X',
    '.XX..XXX',
  ]],
  x: [3, [
    '.XX.XX',
    '...X',
    '..X',
    'XX.XX',
  ]],
  Y: [6, [
    '..XX...X',
    '...X...X',
    '..X....X',
    '..X...X',
    '..X...X',
    '...XXX',
    '.....X',
    'X...X',
    '.XXX',
  ]],
  y: [3, [
    'XX..X',
    '.X..X',
    'X..XX',
    'XXXX.X',
    '...XX',
    '.XX',
    'X.X',
    'XX',
  ]],
  Z: [6, [
    '.XXX..X',
    'X..XXX',
    '....X',
    '...X',
    '..X',
    '.XXX..X',
    'X..XXX',
  ]],
  z: [3, [
    '.XX.X',
    'X..X',
    '..X..X',
    '.X.XX',
  ]],
}

// Columns between one letter's last stitch and the next letter's first.
const TRACKING = 1

// Cells relative to the letter's origin column and the baseline row (the
// baseline row itself is -1, like the rasterized glyphs). The origin is
// the leftmost stitch above the baseline, so a descender swash can tuck
// under the letter before it.
export function chartGlyph([baseline, rows]) {
  const cells = rows.map((row, y) =>
    [...row].flatMap((mark, x) => (mark === 'X' ? [[x, y - baseline - 1]] : [])),
  )
  const body = cells.slice(0, baseline + 1).flat()
  const left = Math.min(...body.map(([x]) => x))
  const right = Math.max(...body.map(([x]) => x))
  return {
    rows: cells.map((row) => row.map(([x, y]) => [x - left, y])),
    advance: right - left + 1 + TRACKING,
  }
}

export const CHARTED_SCRIPT = new Map(
  Object.entries(LETTERS).map(([letter, chart]) => [letter, chartGlyph(chart)]),
)
